### ISSUE TITLE
Tracking issue: implementation of RFC005

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#1121]
Tracking issue for the implementation of RFC005 (#819).

- [x] Restrict metadata to record fields only (#953, #990)
- [x] Lazy propagation for contracts (#1086)
- [ ] Reduce the performance overhead of lazy propagation, e.g. by caching contract application over record fields (https://github.com/tweag/nickel/pull/1086#discussion_r1104635180)
- [ ] Improve the handling of dynamic fields, and how their metadata and pending contracts are transferred (https://github.com/tweag/nickel/pull/1086#discussion_r1104633235)
