### ISSUE TITLE
Performance improvement ideas: tracking issue

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#1484]
Performance is a tricky matter. We want to avoid spending time on implementing changes wishfully improving performance without:

1. A concrete use-case showing that a performance issue is either an actual problem in practice, or is subpar when compared to other languages/tools
2. Principled measurements pointing to functions to be improved, and after implementing a performance-related change, confirming the gain

Still, with time, we've spotted many potential points of congestion and candidates for performance improvements. This issue serves to record those insights, and might be used as a starting point when investigating a performance issue or looking for performance improvements for specific parts of the Nickel pipeline.

This issue isn't concerned with big paradigm shifts such as incremental evaluation or moving towards a bytecode compiler + virtual machine approach. Such topics deserve their own issue/notes/RFC/paper. The ideas here are closely tied to the current implementation, and we want to avoid losing them or ignoring them while they could be relevant.

Feel free to add your own, that I'll try to edit into this description.

## Interpreter

- **Get rid of generated variables**. Currently, we can't directly store a closure (a term and an environment together) into a Nickel AST. One reason is that we only have one AST, and a closure doesn't make any sense at e.g. parsing time, typechecking time and program transformation time. It would be strange to depend on runtime-related definitions for the core AST type. But, during evaluation, we morally need to store closures inside expression (typically, data structures such as arrays and records store closures). The trick we use is to generate a unique variable, bind the closure in the environment, and store this variable in the term instead. This trick leads to a lot of variable generation and variable lookup, which go through the environment, meaning they incur a hashmaps lookup (and, in the worst case, a linear-time lookup, because the environment is more or less a linked list of hashmaps). This is in particular a problem for the share normal form, which, for big terms (large records), might generate a huge load of heading lets binding generated variables, degrading the performance of even just parsing then exporting a Nickel program which is mostly already evaluated (#1428)
- **Cache lazy contract application**. Since RFC005, and previous work on lazy array contracts, Nickel basic datastructures (arrays and records) now apply contracts lazily. That is, applying an array contract or a record contract just attaches data to those structures, but doesn't evaluate anything. When merging records, contracts are still accumulated lazily, without being applied. Only when a field, or an array element is requested (either directly, or via transformations, such as mapping a function over), that the contract are actually applied. However, we currently have to place to cache this contract application. This means that extracting a field or an array element several times will apply pending contracts as many times, while we could cache this result in a thunk and guarantee that it's only executed once. A simple solution would be, for arrays and records, to store a pair of closures `(original, cached)`, where `original` corresponds to the initial value without contracts applied, and `cached` is a fresh thunk (not aliased by anyone else when allocating the array or record) and can serve to store the field with contracts applied.
- **Use contract equality to avoid double contract application**. We implemented contract equality (limited, of course, it's undecidable in general) for typechecking purpose. It wouldn't be very hard to re-use this code to decide contract equality at runtime, and thus avoid double-contract application e.g. at record fields (which lazily record contracts in a vector) or arrays. It might even be adapted to handle stand-alone, inline contract applications, but for that we would need to not evaluate annotated term away to a simple contract application, which we do currently.
- **Use a De Bruijn indices for the environment**. The environment is a linked list of hashmaps, where the linked list mirrors more or less scopes and sharing points. We can make it a big better (in practice, not asymptotically), by using a linked list of arrays and pre-computing the index of each allocated variables, as in De Bruijn indexin (#844)
- **Use a persistant HashMap for the environment**. Alternate experiment to the previous one (#837)

## Typechecker

- **Makes types shareable**. Currently, the AST for `typ::Type` is using owned pointers (`Box`). This means that subtypes aren't shared, and unification of say `a -> b` with `T -> U` needs to perform a deep copy of both `T` and `U`. Possible solutions are to use `Rc` instead of `Box` (as we do for terms), or to use an arena, see below.
- **Use an arena to allocate types**. Related to the previous item: instead of using `Rc`, we could also allocate all types in an arena. Types (or, rather, unification types) have currently a well delimited lifetime: they are allocated as part of a statically typed block, and can't escape this block.
- **Implement a proper union-find data structure, and in particular use direct pointers for unification variables**. Currently, unification variables are indices inside a vector. But they could be direct pointers, eliminating an additional indirection, and eliminating the need to thread the unification table everywhere as well.
- **Implement path compression**. When resolving a unification variable, remember all the variables encountered while following the link in the unification table/union-finnd structure and sets them all to the final result. Doing so, the next resolution will succeed in only one step.

## Program transformation

- **Store direct pointers to nodes to transform**. Some transformations, like import resolution, concerns statistically only very few nodes. Still, we currently traverse the whole term to look for e.g. an import. We could in fact record pointers to imports at parsing time, and process them directly later. The premise isn't entirely true: we have to perform a traversal anyway (in fact, at least two, one bottom-up, and one top-down), for other transformations (such as the free-var transformation or the share normal form, which are probably better to do as a normal traversal). But it might be the case that at least one traversal could be saved, if we find out that all of the transformation phases can be done by recording the nodes to process during parsing, which might be attractive if like import resolution the set of nodes is expected to be small.

**Comment by jneem** [comment]
# LSP

 - [ ] **Faster reference finding**. Definition-finding in LSP is fairly fast, but reference-finding might be slow, as it currently works by identifying many possible references, and then running definition-finding on each one. This could be potentially be improved by running an extra analysis pass that caches all the definition-finding information. Alternatively, we could perform this pass lazily so that the first reference-finding is a little slow but subsequent ones are faster.

**Comment by yannham** [comment]
# Serialization

- [ ] **Spanned deserialization**. We deserialize YAML, JSON and TOML with span information, for error reporting purpose. Currently, the deserialization cost is trumped by AST allocation most likely, but we do introduced potential inefficiencies tot get span: using `saphyr` (which seems to be much slower on pure JSON than `serde_json`), and double deser for JSON to make sure the JSON is really the JSON subset of YAML, and not arbitrary YAML. We could investigate saphyr performance, or switch the JSON validation part to something faster that doesn't need to actually allocate the JSON value. See discussion at https://github.com/tweag/nickel/pull/2382
- [ ] **Avoid substitution**. To be explored as a follow up of #2302. We used to have a lot of generated variable that needed to be substituted before serialization (to avoid having to refer to an external environment). However, now those generated variables are mostly `Closure` (or `Thunk` in the new `NickelValue` representation) that don't refer to an external environment (though they still need the evaluation cache). In any case, even if we need an auxiliary environment, we should probably try to serialization Nickel expressions in one go instead of first traversing the whole AST, and moving stuff around, just to traverse it again.

**Comment by L0r3m1p5um** [comment]
I've noticed a few cases in the LSP where I think it's doing unnecessary work:

Any change to a file invalidates every file that depends on it, so they get typechecked and evaluated again. A lot of times this should not be necessary, because a lot of source changes like writing comments or formatting don't actually change how the file is parsed. If the LSP could detect when the result of a change after parsing is identical to before then it wouldn't need to invalidate the typechecking/evaluation of that file or of any of the files that depend on it. You could say something similar about edits that change how the file is parsed but don't change the type of a file, since the typechecking of any files that import it should still be valid (although reevaluation would still need to happen). 

This is mainly noticeable in projects where the LSP is already slow, but I think that requests for `textDocument/didChange` for the same file will queue up, meaning that the LSP can start analyzing a version of a file that is already out of date.

This is a more minor issue, and I'm not sure how easy it would be to avoid, but opening a file in-memory invalidates it, even before any edits are made. Just to be clear the scenario I'm talking about is:
- File A imports file B
- File A is opened in the editor. Because of the import, the LSP will also parse and typecheck B from the filesystem.
- File B is opened in the editor. The LSP invalidates the typechecking and evaluation of A even though the content of B is still the same as it was on the filesystem at this point.

**Comment by L0r3m1p5um** [comment]
> Any change to a file invalidates every file that depends on it, so they get typechecked and evaluated again. A lot of times this should not be necessary, because a lot of source changes like writing comments or formatting don't actually change how the file is parsed. If the LSP could detect when the result of a change after parsing is identical to before then it wouldn't need to invalidate the typechecking/evaluation of that file or of any of the files that depend on it. You could say something similar about edits that change how the file is parsed but don't change the type of a file, since the typechecking of any files that import it should still be valid (although reevaluation would still need to happen).

On second thought even if some edit does not change the AST, the positions of all the diagnostics _would_ change. So you would still have to rerun typechecking and evaluation at least within the same file. It should still be possible to avoid invalidating all the files that depend on that file I think.

**Comment by yannham** [comment]
The LSP is embarrassingly not incremental indeed. There's the full invalidation problem that you mention, and additionally many non-trivial analyses (like request for references, for document symbols, or whatnot) that can take time on large file aren't cached, so they are slow each and every time, even if the file isn't edited.

There are many ways to improve that. There is prior art in other LSPs, in particular I believe Rust analyzer use an [Adapton](https://dblp.org/rec/conf/pldi/HammerKHF14.html)-based incremental library [salsa](https://github.com/salsa-rs/salsa). The parsing part can be further incrementalized with incremental parsing (as tree-sitter implement). I suppose even typechecking can be made incremental as well, although I don't know much bibliography on this specific topic.

In general I would say there are two approaches (that can be combined as well):

1. A cheap one which is to memoize previous results: whenever one block's output (parsing, typechecking, etc.) doesn't change, we can stop the computation here and re-use previous cached value for the final result of interestt. Truly incremental computations, like incremental parsing, are able to re-use the previous result to perform as few work as possible upon change, which is more powerful than early cut-off but more involved.

**Comment by L0r3m1p5um** [comment]
I took a look at rust-analyzer a bit. Apart from the incrementality, it's also moving most analyses off the main thread, so the main thread is only use for either operations that change the global state, like modifying a source file, or a few very latency sensitive requests that would otherwise block typing. A big thing that makes it work to run those analyses off the main thread like that is all those analyses are also cancellable. So if one thread is doing something like getting diagnostics for a file, and a change to that file's source is made by the main thread, it can stop calculating those diagnostics since they're now out of date. The cancellation is also implemented by salsa I think. I don't know how easy that would be to implement for Nickel. I guess it's sort of done for evaluation, but the background eval tasks also can't use or update the parsing or typechecking caches so I wouldn't want to do everything that way.

I think maybe the easiest thing to do for the performance you'd get is just to manage the main thread's time better. Like when a file is changed, all of its reverse dependencies are typechecked synchronously to the change, so the main thread can spend a lot of time blocked on stuff that's not of immediate relevance. I think it might make more sense to break that down into individual tasks, so that the list of invalidated files would be pushed onto a queue instead, and the main loop could pick one and run the typechecking for it when it doesn't have higher priority work to do. I think at the main loop you would also want to be aware all of the requests or notifications that have come in before starting work on any of them, so it'd be possible to prioritize the important ones and avoid starting work on things that are already obsolete.
