### ISSUE TITLE
Investigate degradation of performance for medium-size codebase (5~10 kLoc)

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#1622]
**Describe the bug**
While I can't produce the code here for privacy reason, I've been personally given a Nickel codebase where the export time is very long (for 5~10kLoC, between 10 and 20s on my laptop). There is no reason that a program of this size is that slow. The code looks rather reasonable, and it means that we are at risk of similar performance degradation for any codebase that reaches this size.

Let's investigate, profile and rely on #1484 to see what's happening and bring that time down to something reasonable.

**To Reproduce**
Can't share the offending code here for privacy reason, unfortunately.

**Expected behavior**
That the export time is low (as a starter, say under a second).

```[tasklist]
### Tasks
- [ ] https://github.com/tweag/nickel/issues/1646
- [ ] https://github.com/tweag/nickel/issues/1648
- [ ] https://github.com/tweag/nickel/issues/1647
- [ ] https://github.com/tweag/nickel/issues/1668
```

**Comment by yannham** [comment]
# Update

The flamegraph isn't very informative, without one big obvious contention point:

![dev-flamegraph](https://github.com/tweag/nickel/assets/6530104/b87e22c1-ce70-4ad7-86a1-47f82ad754d2)

@vkleen's plan is to start adding tracing to various part of the Nickel interpreter to gather finer stats and timing for those kind of use-cases.

In the meantime, I noticed that:

1. A lot of contract application were duplicated. Printing the result (with the default nickel invocation, without `export`) shows things such as `{ some_field | ContractFoo | ContractFoo | ContractFoo | ContractFoo ...}`. I implemented contract deduplication using the contract equality check from the typechecker, which brought down the evaluation time by around 50%. I still think we can reduce the original time by a good order of magnitude.
2. A bazillion of generated variables are created. It's probably stressing the environment (insertion and lookup) _a lot_, and in the worst case, environment can behave as a linked list which could explain the overall performance. The next step is to add a `Closure` node to the AST instead of using generated variables. That is, use pointers directly without environment indirection.

**Comment by marijetamh** [comment]
@yannham is this done, as due date is passed ?

**Comment by yannham** [comment]
While it's not back "under a second", it's consistently back around 3seconds after several optimizations. This is not the end of the story, but work coming next can be done as part of a new tracking issue/epic, I think. We did investigate and applied somehow successfully the first train of optimizations.
