### ISSUE TITLE
Tracking issue for implementation of RFC001 (overriding)

### ISSUE THREAD

**Issue by yannham** [tweag/nickel#843]
# TODO

- [x] Merge priorities : #829
- [x] Recursive merge priorities (`force rec`, `default rec`): #845
- [ ] Custom merge functions, step 1: merge trees
- [ ] Custom merge functions, full
