### ISSUE TITLE
Improve LSP record completion

### ISSUE THREAD

**Issue by ebresafegaga** [tweag/nickel#877]
With #867, we have basic record completion. However, this can be improved in the following areas:

* [x] Record completion for imports (e.g `let r = import "r.ncl" in r[.]`) #993 
    * [x] Record completion for `stdlib` terms (e.g `array[.]` should give correct completion terms) #918
* [x] Nested record completion (e.g `let x = {foo.bar.baz = 1} in x.foo[.]` should get `baz`, `let f : {a:{b:{c:{d:Str}}}} -> Str = fun x => x[.] in f`) #909
  * [x] Quoted fields should be supported too, e.g. `let x = {"fo京o" = {bar = 42}} in x."fo京o".<ctrl space>` #913 
* [x] Use contract metadata to give completions (e.g ` let x | {foo : Num} = null in x[.]`  and `let x | {foo | Num} = null in x[.]`)  #914 
* [x] Recursive record (e.g `{ foo.bar = 1,  baz = foo[.]  }`) #1088
* [x] Record terms should give completion (e.g `({ a = 10})[.]` should get a completion or, more generally, 
      `(<any expr that we know evals to a record>)[.]` )

Note:  `[.]` represents the cursor, after the `.` key has been pressed
